apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  db_host: "my-postgresql.ubble.svc.cluster.local"
  db_port: "5432"
  db_name: "postgres"
  db_user: "usrdev"
  db_password: "pass4Dev"
  