apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ubble-backend
  name: ubble-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubble-backend
  template:
    metadata:
      labels:
        app: ubble-backend
    spec:
      containers:
      - image: csbiti/formulaire_ubble_backend:1.0.5-dev
        imagePullPolicy: Always
        name: formulaire-ubble-backend
        env:
          - name: UBBLE_USE_POSTGRES
            value: "true"
          - name: UBBLE_DB_USER
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db_user
          - name: UBBLE_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                  name: my-postgresql
                  key: password
          - name: UBBLE_DB_HOST
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db_host
          - name: UBBLE_DB_PORT
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db_port
          - name: UBBLE_DB_NAME
            valueFrom:
              configMapKeyRef:
                name: postgres-config
                key: db_name
      restartPolicy: Always