apiVersion: v1
kind: Service
metadata:
  labels:
    app: ubble-frontend
  name: ubble-frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 4200
  selector:
    app: ubble-frontend
  type: LoadBalancer
